### ISSUE TITLE
fix automatic versioning

### ISSUE THREAD

**Issue by pidkopajo** [VirtusLab/formts#62]
Currently, automatic versioning only jumps by minor version regardless of the git history.
Maybe smth needs to be done to `standard-version` configuration

**Comment by pidkopajo** [comment]
@mixvar, `standard-version` doesn't bump the version properly as we don't currently have a major version.
see this issue for more details https://github.com/conventional-changelog/standard-version/issues/429
I've set up a local branch with a major version set to 1, and `feat/fix/BREAKING CHANGE` commits properly bump major/minor/patch versions

**Comment by mixvar** [comment]
awesome, closing the issue
