### ISSUE TITLE
attaching validation rules to individual fields inside arrays

### ISSUE THREAD

**Issue by mixvar** [VirtusLab/formts#82]
for example given the Schema:
```ts
const Schema = createFormSchema(
  fields => ({
    array: fields.array(
      fields.object({
        foo: fields.string(),
        bar: fields.string(),
      })
    ),
  }),
);
```

it should be possible to attach validators to every `array.foo` and `array.bar` fields

**Comment by mixvar** [comment]
| descriptor        | when passed to validate fn           | when passed to useField fn  |
| ------------- |:-------------:| -----:|
| Schema.array      |  validate entire array as a whole  |  get FieldHandle for entire array  |
| Schema.array.nth()    | validate every item in the array       |   N/A (should not compile) |
| Schema.array.nth(0)      |    validate first item of the array | get FieldHandle for first array item |

**Comment by pidkopajo** [comment]
TODO: introduce `.every` method/field on the array for collective validation (instead of overloading`nth()`)
* `array.every` - will validate every item of `array`
* `array.every.foo.bar` - will validate `x.foo.bar for x of array`
